### PR TITLE
for Windows

### PR DESCRIPTION
**Pull request by ivysrono**
BTW, you may need [path.join](https://nodejs.org/api/path.html#path_path_join_paths)

### CODE REVIEW

**Comment by kaorahi** [comment]
Thx for your helpful PR. I agree that we should use path.join anyway.

For the PR itself, I'm not sure whether it is really necessary. I've never heard that one has to modify the source code to use lizgoban on Windows. What problem do you have if you don't apply your PR?

**Comment by ivysrono** [comment]
图片
Windows do not support `npx electron src -j xxxxxxx`, so I have to edit main.js to use.

**Comment by kaorahi** [comment]
Does 246045e4 fix your problem?

**Comment by ivysrono** [comment]
It works. Thanks.

**Pull request closed without merging**
