### PR TITLE
Create WindowsLaunch.vbs

### PR DESCRIPTION
**Pull request by ivysrono**

### CODE REVIEW

**Comment by kaorahi** [comment]
I guess that a simple one-liner may be enough

~~~
' ver1.vbs
CreateObject("Wscript.Shell").Run "npx electron src -c config.json"
~~~

with a default config.json:

~~~
{
  "leelaz_command": "../leelaz",
  "leelaz_args": ["-g", "-w", "../network.gz"]
}
~~~

Or, we may need to set the current directory so that shortcuts to *.vbs work everywhere (on the desktop etc).

~~~
' ver2.vbs
Dim wsh
Set wsh = WScript.CreateObject("WScript.Shell")
wsh.CurrentDirectory = createObject("Scripting.FileSystemObject").getParentFolderName(WScript.ScriptFullName)
wsh.Run "npx electron src -c config.json"
~~~

Are these correct?

**Comment by ivysrono** [comment]
3 difference:

- `%comspec% /c ` will close background cmd auto when we close lizgoban.

- `, 0, true` will hide the cmd black window directly.

- ensure run lizgoban while there is no `config.json`

**Comment by kaorahi** [comment]
What happens if you double-click my ver1.vbs or ver2.vbs?

**Comment by ivysrono** [comment]
ver1.vbs equal to ver2.vbs:
no config.json:
图片
with config.json:
图片

**Comment by kaorahi** [comment]
Thx for the report. I would like to confirm the situation.

1. Is "the cmd black window" shown by ver1.vbs?
2. Is the redundant icon (red arrow in your previous screenshot) shown by the below ver3.vbs?

~~~
' ver3.vbs
CreateObject("Wscript.Shell").Run "notepad"
~~~

**Comment by ivysrono** [comment]
1. yes, the cmd black window show both by ver1.vbs and ver2.vbs
2. no, ver3.vbs launch the notepad without cmd window(the redundant icon)

**Comment by kaorahi** [comment]
Then, how about these? I can't understand why the third argument (true) is needed in Run(...).

~~~
' ver4.vbs
CreateObject("Wscript.Shell").Run("npx electron src -c config.json", 0)
~~~

~~~
' ver5.vbs
CreateObject("Wscript.Shell").Run("%comspec% /c npx electron src -c config.json", 0)
~~~

**Comment by ivysrono** [comment]
图片
the above is ver4, same error for ver5

**Comment by kaorahi** [comment]
Oh, sorry. Would you try ver6.vbs and ver7.vbs? I'd like to understand and simplify your script so that I can maintain it.

~~~
' ver6.vbs
CreateObject("Wscript.Shell").Run "npx electron src -c config.json", 0
~~~

~~~
' ver7.vbs
CreateObject("Wscript.Shell").Run "%comspec% /c npx electron src -c config.json", 0
~~~

**Comment by ivysrono** [comment]
6：
图片

7：
图片

**Comment by kaorahi** [comment]
I intend to confirm necessity of the third argument of Run and %comspec% in these tests before considering the problem of config.json.

~~~
' ver8.vbs
CreateObject("Wscript.Shell").Run "npx electron src", 0
~~~

~~~
' ver9.vbs
CreateObject("Wscript.Shell").Run "%comspec% /c npx electron src", 0
~~~

**Comment by ivysrono** [comment]
They are ok, both.
https://docs.microsoft.com/en-us/previous-versions//d5fk67ky(v=vs.85)
You can remove the third argument of run.
https://autohotkey.com/board/topic/10459-what-does-k-mean-in-comspec/
%comspec% /c is better.

**Comment by kaorahi** [comment]
thx. Hopefully this will be the final version.

1. Does it work?
2. Does a shortcut to ver10.vbs work even if *.lnk is placed on the desktop?
3. Is "%comspec% /c npx electron src" better than "npx electron src"? (Why?)

~~~
' ver10.vbs
Const conf = "config.json"
command = "npx electron src"

Set fso = CreateObject("Scripting.FileSystemObject")
If fso.FileExists(conf) Then
command = command & " -c " & conf
End If

Set sh = CreateObject("WScript.Shell")
sh.CurrentDirectory = fso.GetParentFolderName(WScript.ScriptFullName)
sh.Run command, 0
~~~

**Comment by ivysrono** [comment]
1. it works fine.
2. yes, this is how windows shortcut work.
3. 
Hide but exist on background:  "npx electron src"
Close and not exist on background:  "%comspec% /c npx electron src"

**Comment by kaorahi** [comment]
I have two questions before pushing the code.

1. Does ver10.vbs work without error/stall if you enable debug log ("Debug" menu ==> "Debug log")? Please run it for a few minutes.
2. Is the line "sh.CurrentDirectory = ..." necessary? Does a shortcut to the below ver11.vbs still work if *.lnk is placed on the desktop?

~~~
' ver11.vbs
Const conf = "config.json"
command = "npx electron src"

Set fso = CreateObject("Scripting.FileSystemObject")
If fso.FileExists(conf) Then
command = command & " -c " & conf
End If

Set sh = CreateObject("WScript.Shell")
' (Is this line necessary?)
' sh.CurrentDirectory = fso.GetParentFolderName(WScript.ScriptFullName)
sh.Run command, 0
~~~

Thx for many trials and reports.

**Comment by ivysrono** [comment]
1. I found nothing after enable the debug log for 5 minutes. Where is the log file?

2. yes, ver11 works if .lnk is placed on the desktop.
all .lnk work just as their original place, that is how windows work.

**Comment by kaorahi** [comment]
There is no log file. Debug logs are shown directly on the console.

**Pull request merged**
