### PR TITLE
Drag and drop sgf file

### PR DESCRIPTION
**Pull request by zakki**

### CODE REVIEW

**Comment by kaorahi** [comment]
Thx. Do you have a reason to use your `read_sgf_file` instead of existing `load_sgf`?

**Comment by zakki** [comment]
One reason is it was part of my experimental LizGoban on server branch ( https://github.com/zakki/lizgoban/tree/server-client ), so browser side scripts can't access to a local file path.
And also I didn't know about electron's `File.path` extension.

**Comment by kaorahi** [comment]
I understand your reason. But, hmm... "Reading file contents in renderer side" sounds strange for me in the context of Electron. Do you hope strongly to use the same code between my master branch and your server-client branch? If you don't mind it, I'll modify your PR to use `load_sgf`.

BTW, your branch is interesting. Why do you avoid the popular way (talk GTP to Leela Zero on a fast server through ssh)?

**Comment by zakki** [comment]
I don't mind it.

Lizzie & ssh requires PC, JRE and ssh.
If LizGoban runs on server, it is usable everywhere using a web browser on PC, tablets or smartphones.

Besides that, ssh seems to be bit difficulty to non programmer users.
The problem is that running node.js on a server is difficult too.

**Comment by kaorahi** [comment]
I use your implementation after all since I realize that I cannot get the path of the dragged file for security. Thx!

https://developer.mozilla.org/en-US/docs/Web/API/File/name

**Pull request merged**
